%General Mission Analysis Tool(GMAT) Script
%Created: 2024-05-01 13:05:51


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft Nave;
GMAT Nave.DateFormat = TAIModJulian;
GMAT Nave.Epoch = '21545';
GMAT Nave.CoordinateSystem = EarthMJ2000Eq;
GMAT Nave.DisplayStateType = Keplerian;
GMAT Nave.SMA = 8000.000000000001;
GMAT Nave.ECC = 2.852150321103344e-16;
GMAT Nave.INC = 0;
GMAT Nave.RAAN = 0;
GMAT Nave.AOP = 0;
GMAT Nave.TA = 0;
GMAT Nave.DryMass = 850;
GMAT Nave.Cd = 2.2;
GMAT Nave.Cr = 1.8;
GMAT Nave.DragArea = 15;
GMAT Nave.SRPArea = 1;
GMAT Nave.SPADDragScaleFactor = 1;
GMAT Nave.SPADSRPScaleFactor = 1;
GMAT Nave.AtmosDensityScaleFactor = 1;
GMAT Nave.ExtendedMassPropertiesModel = 'None';
GMAT Nave.NAIFId = -10000001;
GMAT Nave.NAIFIdReferenceFrame = -9000001;
GMAT Nave.OrbitColor = Red;
GMAT Nave.TargetColor = Teal;
GMAT Nave.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT Nave.CdSigma = 1e+70;
GMAT Nave.CrSigma = 1e+70;
GMAT Nave.Id = 'SatId';
GMAT Nave.Attitude = CoordinateSystemFixed;
GMAT Nave.SPADSRPInterpolationMethod = Bilinear;
GMAT Nave.SPADSRPScaleFactorSigma = 1e+70;
GMAT Nave.SPADDragInterpolationMethod = Bilinear;
GMAT Nave.SPADDragScaleFactorSigma = 1e+70;
GMAT Nave.AtmosDensityScaleFactorSigma = 1e+70;
GMAT Nave.ModelFile = 'aura.3ds';
GMAT Nave.ModelOffsetX = 0;
GMAT Nave.ModelOffsetY = 0;
GMAT Nave.ModelOffsetZ = 0;
GMAT Nave.ModelRotationX = 0;
GMAT Nave.ModelRotationY = 0;
GMAT Nave.ModelRotationZ = 0;
GMAT Nave.ModelScale = 1;
GMAT Nave.AttitudeDisplayStateType = 'Quaternion';
GMAT Nave.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT Nave.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT Nave.EulerAngleSequence = '321';

%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft Det;
GMAT Det.DateFormat = TAIModJulian;
GMAT Det.Epoch = '21545';
GMAT Det.CoordinateSystem = EarthMJ2000Eq;
GMAT Det.DisplayStateType = Keplerian;
GMAT Det.SMA = 10000.93881762902;
GMAT Det.ECC = 1.782761303752219e-16;
GMAT Det.INC = 0;
GMAT Det.RAAN = 0;
GMAT Det.AOP = 0;
GMAT Det.TA = 0;
GMAT Det.DryMass = 850;
GMAT Det.Cd = 2.2;
GMAT Det.Cr = 1.8;
GMAT Det.DragArea = 15;
GMAT Det.SRPArea = 1;
GMAT Det.SPADDragScaleFactor = 1;
GMAT Det.SPADSRPScaleFactor = 1;
GMAT Det.AtmosDensityScaleFactor = 1;
GMAT Det.ExtendedMassPropertiesModel = 'None';
GMAT Det.NAIFId = -10000001;
GMAT Det.NAIFIdReferenceFrame = -9000001;
GMAT Det.OrbitColor = Red;
GMAT Det.TargetColor = Teal;
GMAT Det.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT Det.CdSigma = 1e+70;
GMAT Det.CrSigma = 1e+70;
GMAT Det.Id = 'SatId';
GMAT Det.Attitude = CoordinateSystemFixed;
GMAT Det.SPADSRPInterpolationMethod = Bilinear;
GMAT Det.SPADSRPScaleFactorSigma = 1e+70;
GMAT Det.SPADDragInterpolationMethod = Bilinear;
GMAT Det.SPADDragScaleFactorSigma = 1e+70;
GMAT Det.AtmosDensityScaleFactorSigma = 1e+70;
GMAT Det.ModelFile = 'aura.3ds';
GMAT Det.ModelOffsetX = 0;
GMAT Det.ModelOffsetY = 0;
GMAT Det.ModelOffsetZ = 0;
GMAT Det.ModelRotationX = 0;
GMAT Det.ModelRotationY = 0;
GMAT Det.ModelRotationZ = 0;
GMAT Det.ModelScale = 1;
GMAT Det.AttitudeDisplayStateType = 'Quaternion';
GMAT Det.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT Det.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT Det.EulerAngleSequence = '321';

%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
GMAT DefaultProp_ForceModel.CentralBody = Earth;
GMAT DefaultProp_ForceModel.PrimaryBodies = {Earth};
GMAT DefaultProp_ForceModel.Drag = None;
GMAT DefaultProp_ForceModel.SRP = Off;
GMAT DefaultProp_ForceModel.RelativisticCorrection = Off;
GMAT DefaultProp_ForceModel.ErrorControl = RSSStep;
GMAT DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.Order = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
GMAT DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
GMAT DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
GMAT DefaultProp.Type = RungeKutta89;
GMAT DefaultProp.InitialStepSize = 60;
GMAT DefaultProp.Accuracy = 9.999999999999999e-12;
GMAT DefaultProp.MinStep = 0.001;
GMAT DefaultProp.MaxStep = 2700;
GMAT DefaultProp.MaxStepAttempts = 50;
GMAT DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create ImpulsiveBurn T01;
GMAT T01.CoordinateSystem = Local;
GMAT T01.Origin = Earth;
GMAT T01.Axes = VNB;
GMAT T01.Element1 = 0;
GMAT T01.Element2 = 0;
GMAT T01.Element3 = 0;
GMAT T01.DecrementMass = false;
GMAT T01.Isp = 300;
GMAT T01.GravitationalAccel = 9.81;
%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
GMAT DefaultOrbitView.SolverIterations = None;
GMAT DefaultOrbitView.UpperLeft = [ 0.3125 0.0537037037037037 ];
GMAT DefaultOrbitView.Size = [ 0.9872448979591837 0.9425925925925925 ];
GMAT DefaultOrbitView.RelativeZOrder = 7;
GMAT DefaultOrbitView.Maximized = true;
GMAT DefaultOrbitView.Add = {Nave, Det, Earth};
GMAT DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.DrawObject = [ true true ];
GMAT DefaultOrbitView.DataCollectFrequency = 1;
GMAT DefaultOrbitView.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView.NumPointsToRedraw = 0;
GMAT DefaultOrbitView.ShowPlot = true;
GMAT DefaultOrbitView.MaxPlotPoints = 20000;
GMAT DefaultOrbitView.ShowLabels = true;
GMAT DefaultOrbitView.ViewPointReference = Nave;
GMAT DefaultOrbitView.ViewPointVector = [ 0 0 0 ];
GMAT DefaultOrbitView.ViewDirection = Earth;
GMAT DefaultOrbitView.ViewScaleFactor = 1;
GMAT DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.ViewUpAxis = Z;
GMAT DefaultOrbitView.EclipticPlane = Off;
GMAT DefaultOrbitView.XYPlane = On;
GMAT DefaultOrbitView.WireFrame = Off;
GMAT DefaultOrbitView.Axes = On;
GMAT DefaultOrbitView.Grid = Off;
GMAT DefaultOrbitView.SunLine = Off;
GMAT DefaultOrbitView.UseInitialView = On;
GMAT DefaultOrbitView.StarCount = 7000;
GMAT DefaultOrbitView.EnableStars = Off;
GMAT DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
GMAT DefaultGroundTrackPlot.SolverIterations = Current;
GMAT DefaultGroundTrackPlot.UpperLeft = [ 0.3125 0.0537037037037037 ];
GMAT DefaultGroundTrackPlot.Size = [ 0.9872448979591837 0.9425925925925925 ];
GMAT DefaultGroundTrackPlot.RelativeZOrder = 3;
GMAT DefaultGroundTrackPlot.Maximized = true;
GMAT DefaultGroundTrackPlot.Add = {Nave, Det};
GMAT DefaultGroundTrackPlot.DataCollectFrequency = 1;
GMAT DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
GMAT DefaultGroundTrackPlot.NumPointsToRedraw = 0;
GMAT DefaultGroundTrackPlot.ShowPlot = true;
GMAT DefaultGroundTrackPlot.MaxPlotPoints = 20000;
GMAT DefaultGroundTrackPlot.CentralBody = Earth;
GMAT DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';

%----------------------------------------
%---------- Arrays, Variables, Strings
%----------------------------------------
Create Variable T01_start T02_start T03_start T04_start T05_start d_nave d_det d1_nave d1_det v1_nave;
Create Variable v1_det nx ny nz nvx nvy nvz dx dy dz;
Create Variable dvx dvy dvz v1 v2 v3 v4;
GMAT T01_start = 0;
GMAT T02_start = 0;



%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;

Propagate 'ParkingOrbit' DefaultProp(Nave, Det) {Nave.ElapsedSecs = T01_start};
GMAT v1 = sqrt((Nave.EarthMJ2000Eq.X*Nave.EarthMJ2000Eq.X)+(Nave.EarthMJ2000Eq.Y*Nave.EarthMJ2000Eq.Y)+(Nave.EarthMJ2000Eq.Z*Nave.EarthMJ2000Eq.Z));
Maneuver T01(Nave);
Propagate 'Rendezvous' DefaultProp(Nave, Det) {Nave.ElapsedSecs = T02_start};
GMAT v2 = sqrt((Nave.EarthMJ2000Eq.X*Nave.EarthMJ2000Eq.X)+(Nave.EarthMJ2000Eq.Y*Nave.EarthMJ2000Eq.Y)+(Nave.EarthMJ2000Eq.Z*Nave.EarthMJ2000Eq.Z));
Propagate 'Rendezvous' DefaultProp(Nave, Det) {Nave.ElapsedSecs = 1};

GMAT nx = Nave.EarthMJ2000Eq.X;
GMAT ny = Nave.EarthMJ2000Eq.Y;
GMAT nz = Nave.EarthMJ2000Eq.Z;
GMAT nvx = Nave.EarthMJ2000Eq.VX;
GMAT nvy = Nave.EarthMJ2000Eq.VY;
GMAT nvz = Nave.EarthMJ2000Eq.VZ;


GMAT dx = Det.EarthMJ2000Eq.X;
GMAT dy = Det.EarthMJ2000Eq.Y;
GMAT dz = Det.EarthMJ2000Eq.Z;
GMAT dvx = Det.EarthMJ2000Eq.VX;
GMAT dvy = Det.EarthMJ2000Eq.VY;
GMAT dvz = Det.EarthMJ2000Eq.VZ;
